name: "✨ 기능 요청"
description: "새로운 기능이나 개선 사항을 요청합니다."
title: "[FEAT] "
labels:
  - enhancement
assignees:
  - your-github-username

body:
  - type: markdown
    attributes:
      value: |
        ## 기능 요청서
        새로운 기능이나 개선 사항이 있다면 아래 양식을 작성해 주세요.

  - type: textarea
    id: background
    attributes:
      label: "배경"
      description: "기능을 요청하게 된 이유와 배경을 간단하게 적어주세요."
      placeholder: "예: 사용자가 경기 검색을 더 쉽게 할 수 있도록 필터 기능이 필요함"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "상세 설명"
      description: "요청하는 기능이 무엇인지 구체적으로 설명해주세요."
      placeholder: "예: 위치, 날짜, 참가 인원으로 경기를 필터링할 수 있도록 구현"
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: "해야할 일"
      options:
        - label: "기능 상세 요구사항 정의"
        - label: "기능 구현"
        - label: "문서/가이드 업데이트"

  - type: textarea
    id: done
    attributes:
      label: "완료 조건"
      description: "기능이 완료되었다고 판단할 수 있는 기준을 작성해주세요."
      placeholder: "예: 필터링된 경기 목록이 정상적으로 표시됨"

  - type: textarea
    id: reference
    attributes:
      label: "참고 자료"
      description: "관련 자료나 레퍼런스 링크를 추가해주세요."

  - type: input
    id: reference-issue
    attributes:
      label: "관련 이슈 번호"
      placeholder: "#123"