server:
  port: 8081
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 테스트 편의용
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
  show-actuator: true

jwt:
  issuer: fliqo-auth
  audience: fliqo-services
  secret: ${JWT_SECRET}
  header-injection:
    enabled: true
    user-id-claim: "sub"
    roles-claim: "roles"

auth:
  access-min: 1440
  refresh-day: 7